services:
  server:
    build:
      context: .
    ports:
      - 8081:8081
    volumes:
      - sqlite-data:/app/database
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
volumes:
  sqlite-data:
